name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: >-
        TIMESTAMP=$(date -u +%Y%m%d%H%M%S)
        SHORT_SHA=$(git rev-parse --short HEAD)
        docker build docker --file alpine.Dockerfile --tag kruxia/svn:alpine
        docker tag kruxia/svn:alpine kruxia/svn:alpine-$TIMESTAMP-$SHORT_SHA
        docker tag kruxia/svn:alpine kruxia/svn
        docker build docker --file buster-slim.Dockerfile --tag kruxia/svn:buster-slim
        docker tag kruxia/svn:alpine kruxia/svn:buster-slim-$TIMESTAMP-$SHORT_SHA
