name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: >-
        docker build docker --file Dockerfile.alpine --tag kruxia/svn:alpine
        docker tag kruxia/svn:alpine kruxia/svn:alpine-$(date +%s)
        docker tag kruxia/svn:alpine kruxia/svn
        docker build docker --file Dockerfile.buster-slim --tag kruxia/svn:buster-slim
        docker tag kruxia/svn:alpine kruxia/svn:buster-slim-$(date +%s)
        
